### ISSUE TITLE
Plugin error for mode:alarm-host

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-vmware#10]
Hello team,

I use the vmware connector for approx 20 hosts, and it works fine. For one host, there are 2 alarms with issue (other checks are ok).
![cap 2016-01-03 a 11 17 02](https://cloud.githubusercontent.com/assets/10330979/12078294/5e3c0f06-b20c-11e5-923b-cd8646484c1d.png)
If I test in command line with verbose:
UNKNOWN: VMWare error (verbose mode for more details) | 'alarm_warning'=0;;;0; 'alarm_critical'=0;;;0;
Can't call method "type" on an undefined value at /usr/local/share/perl5/VMware/VICommon.pm line 1501.
Checking host xxxx.example.com
    0 warn alarm(s) found(s) - 0 critical alarm(s) found(s)

The same check works on other hosts, so, it couldn't be a Perl package issue, no?

**Comment by garnier-quentin** [comment]
All are ESXi ? What are the ESX version (not the same maybe) ?

**Comment by matthieu-robin** [comment]
There are 2 versions on the infrastructure, ESXi 5 and 5.5.
All works fine except this one. We have already try to restart it without success… :-(

Matthieu ROBIN
0041 79 746 93 05
0033 6 51 42 92 09
www.matthieurobin.com
info@matthieurobin.com

**Comment by garnier-quentin** [comment]
COuld you go to the cmdalarmhost.pm file and replace:
my $entity = centreon::vmware::common::get_view($self->{connector}, $_->entity, ['name']);

By:

my $entity = centreon::vmware::common::get_view($self->{connector}, $_->entity, ['name', 'type']);

**Comment by garnier-quentin** [comment]
FOrget for the last response. Not that.

**Comment by matthieu-robin** [comment]
You’re right, it’s not that. Same error message

Matthieu ROBIN
0041 79 746 93 05
0033 6 51 42 92 09
www.matthieurobin.com
info@matthieurobin.com

**Comment by garnier-quentin** [comment]
Do you use the last version ? You shouldn't have the following line: 

my $alarmMgr = centreon::vmware::common::get_view($self->{connector}, $self->{connector}->{session1}->get_service_content()->alarmManager, undef);

**Comment by matthieu-robin** [comment]
I have the latest, and I have checked, I don’t have this line.

Thanks

Matthieu ROBIN
0041 79 746 93 05
0033 6 51 42 92 09
www.matthieurobin.com
info@matthieurobin.com

**Comment by garnier-quentin** [comment]
It seems like a generic error (maybe the sdk version, a sdk bug or other). You can send me a mail for a webex next week.

**Comment by matthieu-robin** [comment]
Sure, will do!
Thanks a lot to work on a sunday! 
 :-)

Thanks Quentin!

Matthieu ROBIN
0041 79 746 93 05
0033 6 51 42 92 09
www.matthieurobin.com
info@matthieurobin.com

**Comment by garnier-quentin** [comment]
It was already fixed in 2.1.0 version. Thanks for your time.
