### ISSUE TITLE
Does the plugin work with vSphere 7 ?

### ISSUE THREAD

**Issue by coucou2000** [centreon/centreon-vmware#126]
Hi,

When i deployed it with my vsphere 7 infra, i got the following errors :

**UNKNOWN: Cannot find 'HostSystem' object**

On the log :

**'default' SOAP request error - possibly a protocol issue: Status read failed:  at /usr/share/perl5/vendor_perl/Net/HTTP/Methods.pm line 282.**

Another question, what version of VSphere Perl SDK should i install ?

Thanks for your help !

**Comment by coucou2000** [comment]
any return ?

**Comment by garnier-quentin** [comment]
Could you test the daemon with mode ```getmap``` ? (to see the esx, virtual machines)

**Comment by coucou2000** [comment]
I got the same error : UNKNOWN: Cannot find 'HostSystem' object

FYI, i tried with Perl SDK 6.7 and 7.02.

**Comment by coucou2000** [comment]
After several tests, getmap works, when i deleted the --esx-hostname parameter

**Comment by garnier-quentin** [comment]
And you should identify the right esx hostname

**Comment by coucou2000** [comment]
> And you should identify the right esx hostname

When i add the right esx hostname to the command, i got the "Cannot find 'HostSystem' object" error, below is the command i run 

/usr/lib/centreon/plugins//centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=getmap --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='default'  --esx-hostname='myhostname.mydomain'

**Comment by garnier-quentin** [comment]
Could you show me the getmap output ? (without --esx-hostname option)

**Comment by coucou2000** [comment]
something like this :

List ESX host(s):
  host1.mydomain [v7.0.3] :
      vm1 [poweredOn]
      vm2 [poweredOn]
      vm3 [poweredOn]   
  host2.mydomain [v7.0.3] :
      vm4 [poweredOn]
      vm5 [poweredOn]
      vm6 [poweredOn]

**Comment by garnier-quentin** [comment]
So it should work with the hostname ```host1.mydomain```

**Comment by coucou2000** [comment]
yes that is what i did, but no luck. and i also tried with the IP adresses of the hosts, i got the same issue

**Comment by coucou2000** [comment]
it works ! the hostname is case sensitive ! SORRY

**Comment by garnier-quentin** [comment]
Great! There is an option in the daemon to set case insensitive: ```case_insensitive => 1```

**Comment by coucou2000** [comment]
Thanks much, I hadn't thought of that, since it's just a dns name.

Now, almost everything works. I just have an issue on the host-memory mode :

UNKNOWN: Cannot get counter 'mem.state.latest' for the sampling period '300' (counter level: 2, sampling level: 1)

Do you have an idea ?

**Comment by garnier-quentin** [comment]
Check the help you'll see an option ;)

**Comment by coucou2000** [comment]
got it , thanks 💯
