### ISSUE TITLE
apps::vmware::connector::plugin - mode memory-vm

### ISSUE THREAD

**Issue by gerpion** [centreon/centreon-vmware#13]
Hello,

I've got a problem with the apps::vmware::connector::plugin plugin.

Works well when i want to get the CPU VM info :

./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --verbose --mode=cpu-vm --vm-hostname cbh14
OK: 'cbh14' Total Average CPU usage 8.50 %, Total Average CPU 1765.00 Mhz, CPU ready 4.03 % on last 5 min | 'cpu_total'=8.50%;;;0;100 'cpu_total_MHz'=1765.00MHz;;;0; 'cpu_ready'=4.03%;;;0; 'cpu_0_MHz'=231.00MHz;;;0; 'cpu_1_MHz'=287.00MHz;;;0; 'cpu_2_MHz'=206.00MHz;;;0; 'cpu_3_MHz'=210.00MHz;;;0; 'cpu_4_MHz'=184.00MHz;;;0; 'cpu_5_MHz'=198.00MHz;;;0; 'cpu_6_MHz'=189.00MHz;;;0; 'cpu_7_MHz'=197.00MHz;;;0;

But not with the memory info :

./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --verbose --mode=memory-vm --vm-hostname cbh14 --sampling-period 300 --debug
UNKNOWN: Cannot get counter 'mem.active.average' for the sampling period '300' (counter level: 2, sampling level: 1) |

Any clue ?

Regards,

**Comment by garnier-quentin** [comment]
You need to configure the statistics configuration in your vcenter. By default it's 1 for all sampling periods.
Interesting link:
http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.vsphere.vcenterhost.doc%2FGUID-25800DE4-68E5-41CC-82D9-8811E27924BC.html

**Comment by gerpion** [comment]
Bonjour Quentin,
Les essais ci-dessous ont été réalisés sur une CES avec Centreon 2.7. Les contrôles de la CPU marche mais pas la mémoire.
J'ai un centreon 2.6.6 à côté de ça, je prend la même commande et ça marche parfaitement.
Il me semble pourtant que j'ai installé correctement tous les prérequis donc je ne vois pas d'où peut venir le souci.
A priori tout est ok sur VMWARE étant donné que le Centreon 2.6.6 est le serveur de prod et que les contrôles de mémoire fonctionnent bien.

**Comment by garnier-quentin** [comment]
Ce n'est pas lié à la version de centreon mais du connecteur vmware. En version 2.1.0 de centreon-vmware, je vérifie plus finement les niveaux de statistiques. 
L'erreur est logique. Il faut configurer les statistiques vmware pour avoir plus d'informations dans la base du vcenter.

**Comment by gerpion** [comment]
Je viens de voir avec mon admin VMWARE, on est passé sur le niveau 2 et ..... ça marche !!
Merci Quentin, efficace comme à chaque fois.
Tous mes voeux pour 2016.

**Comment by garnier-quentin** [comment]
You' re welcome ;)

**Comment by sergio78180** [comment]
Bonjour,

Après avoir modifié ce paramètre au niveau du VCenter, est-il nécessaire de le redémarré ?

Car j'ai toujours le statut UNKNOWN.

Pour info, moi c'est dans le cadre du trafic pour les vmnic :
UNKNOWN: Cannot get counter 'net.received.average' for the sampling period '300' (counter level: 2, sampling level: 1)

D'avance merci,

Serge

**Comment by garnier-quentin** [comment]
Il est nécessaire de redémarrer le connecteur vmware.

**Comment by sergio78180** [comment]
Muchas gracias ! ;)

**Comment by alinabrinza95** [comment]
Hello, I'm facing the same problem.
I have 3 vcenters, one of them works perfectly but 2 of them are giving me the following error for every ESX i have there: UNKNOWN: Cannot get value for counters (Maybe, object(s) cannot be reached: disconnected, not running, time not synced (see time-host mode),...). I looked up on Vsphere, and i can't see any graphics for the memory. I also checked the NTP and it's ok. I have an extra option for the script: --sampling-period 20 but the output unknown doesn't change. Could you please help?
Thank you in advance.

**Comment by alinabrinza95** [comment]
Moreover, I changed in Vsphere to level 2 as you indicated above.
I don;t know what else to do.
P.S I also know french if you are able to help me on this issue.
Thanks again.

**Comment by ITNicoz** [comment]
Have you restart centreon_vmware deamon.
(root@XXX)# service centreon_vmware restart
It's OK for me.
Thx Quentin.
