### ISSUE TITLE
apps::vmware::connector::plugin, the option "--unit" doesn't work

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-vmware#16]
Hello,
After installing  centreon-plugins-base-1.15 on my centreon 2.7.1, the option "--unit" doesn't work anymore for the plugin apps::vmware::connector::plugin. The following message appears: 
"Unknown option: unit at /usr/lib/nagios/plugins/centreon-lugins/centreon/plugins/alternative/Getopt.pm line 66". (even if we use '%' or 'B').

Regards,

**Comment by garnier-quentin** [comment]
It's --units. Not a bug from vmware connector ;)
