### ISSUE TITLE
Mode vmoperation-cluster - Always 'Buffer Creation'

### ISSUE THREAD

**Issue by dooko** [centreon/centreon-vmware#18]
Hi,
The mode "vmoperation-cluster" is always creating his buffer.
I don't see nothing on '/var/lib/centreon/centplugins/'.
Do I miss something ?
Thanks

**Comment by garnier-quentin** [comment]
Hi,

Could you give me your command line ?

**Comment by dooko** [comment]
./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=vmoperation-cluster --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='***'  --cluster='.*' --filter --verbose

**Comment by dooko** [comment]
Well this morning it created a cache file when launched manually :
cache_vmware_connector_*_vmoperationcluster_4fd4a56c435d5c26b3c3c366f51b074e

**Comment by garnier-quentin** [comment]
So it's ok ?

**Comment by dooko** [comment]
Yes, no problem for the last 4 days.
Thanks
