### ISSUE TITLE
list-esxhost to use with centreon-auto-discovery-server

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-vmware#19]
Hello Quentin,

Is it possible to add a new mode to discover Esx Host managed by a vCenter with centreon-auto-discovery-server ?

It would create any new ESX host following a host template and optionaly modify /etc/centreon/centreon_vmware.pm for direct controls.
It would disable any ESX host which have been deleted from vCenter.

Thanks.

**Comment by garnier-quentin** [comment]
Hi Dominique,

centreon-auto-discover-server cannot add hosts.
You can monitor esx host without added it in "centreon_vmware.pm". You have options in centreon-plugins client.

**Comment by ritouret** [comment]
Thank you Quentin,

Is there any other way to add hosts in centreon with a similar way from centreon-auto-discover-server ?

**Comment by garnier-quentin** [comment]
Don't know a module for that.
