### ISSUE TITLE
[enhancement][mode] Mode to monitor if CD or DVD is plugged on VMs

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon-vmware#20]
Hi,

As you do for the global vmtools or snapshot check. Could you add a mode to monitor if a CD or DVD is plugged on VMs.

Thanks

**Comment by garnier-quentin** [comment]
You want to know if there is a cdrom/dvd configured for the virtual machine ? Or if there is an ISO image attached ?

**Comment by Sims24** [comment]
Yes if an iso is attached

**Comment by garnier-quentin** [comment]
An example of the command:
```
centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=device-vm --connector-hostname='localhost' --container='default'  --verbose  --device='VirtualCdrom'  --disconnect-status='ok' --nopoweredon-status='ok' --warning=0
```
