### ISSUE TITLE
Startup script doesn't work

### ISSUE THREAD

**Issue by rk4an** [centreon/centreon-vmware#21]
Hi,

In Debian Jessie 8.4, startup script didn't work.

When I start it manually, it only work on /usr/lib/nagios/plugins, if not, I have this error:

```
 /usr/bin/centreon_vmware.pl
 Possible precedence issue with control flow operator at /usr/local/share/perl/5.20.2/VMware/VICommon.pm line 2147.
 Can't locate centreon/plugins/options.pm in @INC (you may need to install the centreon::plugins::options module) (@INC contains: /usr/bin /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /usr/share/perl5/centreon/vmware/common.pm line 28.
 BEGIN failed--compilation aborted at /usr/share/perl5/centreon/vmware/common.pm line 28.
 Compilation failed in require at /usr/share/perl5/centreon/script/centreon_vmware.pm line 33.
 BEGIN failed--compilation aborted at /usr/share/perl5/centreon/script/centreon_vmware.pm line 33.
 Compilation failed in require at /usr/bin/centreon_vmware.pl line 23.
 BEGIN failed--compilation aborted at /usr/bin/centreon_vmware.pl line 23.
```

Any idea?

Regards,

**Comment by garnier-quentin** [comment]
Do you find following file on the system ?
centreon/plugins/options.pm

**Comment by rk4an** [comment]
Yes I have it

 /usr/lib/nagios/plugins/centreon/plugins/options.pm

Change startup script to

`
  start-stop-daemon --start --background --quiet --pidfile ${PIDFILE} --exec ${DAEMON} \
    --make-pidfile --chuid ${CENTREON_USER} --user ${CENTREON_USER} -d /usr/lib/nagios/plugins/ -- $OPTIONS
  [ "$?" = "0" ] || return 2`

And it works now

**Comment by garnier-quentin** [comment]
The libraries need to be installed in @INC perl PATH. Or the binary must be at the root (where 'centreon/plugins/options.pm'.
