### ISSUE TITLE
Check datastore-vm doesn't work with VMware Virtual SAN.

### ISSUE THREAD

**Issue by nakasix** [centreon/centreon-vmware#22]
Hello,

While checking datastore-vm on Virtual Machine using a Virtual SAN. The plugin returns "UNKNOWN: Cannot get value for counters (Maybe, object(s) cannot be reached: disconnected, not running,...) |"

Best regards and sorry for my bad english.

**Comment by garnier-quentin** [comment]
What do you mean by virtual SAN ? You mean RDM disks ?

**Comment by nakasix** [comment]
Not RDM disks. Virtual SAN is hyper-converged storage solution ! The datasheet of product is here : http://www.vmware.com/products/virtual-san/.

**Comment by garnier-quentin** [comment]
Need to look and know more about it. Could we get a teamview or webex ?

**Comment by stefanotoro** [comment]
Hi, any news for this input ?
The plugin does not work now.
Thank you
Best regards
