### ISSUE TITLE
Cannot get response

### ISSUE THREAD

**Issue by Sadric** [centreon/centreon-vmware#27]
Hello,

When i launch the following command :

 perl centreon_plugins.pl --plugin=apps::vmware::connector::plugin  --custommode=connector --connector-hostname=127.0.0.1 --container=default --verbose --mode=health-host --esx-hostname='.*' --filter --disconnect-status='ok'

i get this error : UNKNOWN: Cannot get response (timeout received) 

Can you help me ?

**Comment by garnier-quentin** [comment]
The daemon is well launched ? Could you launch it manually with option --severity=debug ?

**Comment by Sadric** [comment]
the daemon was not launched
Sorry my bad :(
tanks for the fast reply

**Comment by garnier-quentin** [comment]
My pleasure.
