### ISSUE TITLE
filter with mode tools-vm

### ISSUE THREAD

**Issue by Sadric** [centreon/centreon-vmware#28]
Hello,

I use tools vm mode, but i have issues with the filter.

All my server name starts with "SRV" so i can filter with that, but i need to exclude all servers with name finish by "replica"

Is it possible ?

tanks

**Comment by garnier-quentin** [comment]
Maybe you can try following regexp --vm-hostname='^(?!([^S][^R][^V].*|SRV-.*-replica)$)'

**Comment by Sadric** [comment]
i can't use '' in centreon UI 

![image](https://cloud.githubusercontent.com/assets/20931166/17586186/682ab302-5fc0-11e6-9ca3-86b417b4add9.png)

**Comment by garnier-quentin** [comment]
Set it in a macro of service. And don't use that test plugin

**Comment by Sadric** [comment]
I test it in a macro of service, but it's the same.
Server who name finish by replica isn't hidden

**Comment by garnier-quentin** [comment]
Could you get the command from centreon_storage database ?
```
SELECT command_line FROM services WHERE command_line llike '%tools-vm%';
```
