### ISSUE TITLE
Add user and size of snapshot

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon-vmware#32]
Hi, is it possible to add in the apps::vmware::connector::plugin and mode snapshot-vm the name of theguy who made the snapshot and the size of each snapshot ?

Thanks in advance!

**Comment by garnier-quentin** [comment]
For the size, you can use the mode ```datastore-snapshot```. For the user, we cannot get that information (it's not saved with it).
Maybe, we can get it from the past tasks. I'm not sure we can query it (table VPX_TASK) with the sdk. If you find how to do it with an example script, please comment it and we could maybe add it
