### ISSUE TITLE
[CES Poller] centreon-vmware Installation with rpm

### ISSUE THREAD

**Issue by sulian** [centreon/centreon-vmware#36]
Hello

I'm using a new Centreon Poller and when I try to install the connector:

``yum install ces-plugins-Virtualization-VMWare-daemon``

and the client:

``yum install ces-plugins-Virtualization-VMWare-client``

I get the following error : 

``No package ces-plugins-Virtualization-VMWare-daemon available.``

and

``No package ces-plugins-Virtualization-VMWare-client available.``

I have installed already perl-VMware-vSphere successfully

Anything I have missed ??

Sulian

**Comment by alliria98** [comment]
Hey
I got the same problem so if you got the answer ;) let me know

**Comment by garnier-quentin** [comment]
Which version of centos/rhel ?

**Comment by alliria98** [comment]
I guess it's version 6

**Comment by garnier-quentin** [comment]
I see it here: 
http://yum.centreon.com/standard/3.0/stable/noarch/RPMS/

**Comment by alliria98** [comment]
How to get it then ? Where should i put those files if i just download them "manually" ?

**Comment by garnier-quentin** [comment]
You have the repo file here:
http://yum.centreon.com/standard/3.0/stable/ces-standard.repo

**Comment by alliria98** [comment]
I'm sorry but I'm not familiar with linux environment and I don't know how to add those repositories :(
I'm really sorry for those "dummies issues"

**Comment by garnier-quentin** [comment]
You should look the redhat/centos documentation. It will be too long to explain here.

**Comment by alliria98** [comment]
OK I'll do that then
Thanks a lot once again

**Comment by alliria98** [comment]
OK I edited the file /etc/yum.repos.d/centreon.repo and I added at the end of the file the information from http://yum.centreon.com/standard/3.0/stable/ces-standard.repo
Then the yum request is OK

once again thank you very much :)

**Comment by sulian** [comment]
It seens that admins must add manually the ces-standard.repo.
