### ISSUE TITLE
Error message when using plugin=apps::vmware::connector::custom::connector.pm

### ISSUE THREAD

**Issue by alliria98** [centreon/centreon-vmware#37]
First of all, i followed https://github.com/centreon/centreon-vmware/blob/master/doc/en/installation/index.rst and installed with yum the package

When I want to request one of my ESX, i got an error message I don't understand : 

![image](https://cloud.githubusercontent.com/assets/26572075/24545731/a54671fa-1608-11e7-8527-9d629af50284.png)

I understand there is one more action to do, but don't know exactly what and how

Thx in advance for your help

**Comment by alliria98** [comment]
This problem is fixeb, but a new one appeared...
I configured the file /etc/centreon/centreon_vmware.pm with a my vcenter IP and allowed credentials

Then when I try to do a request, this happens : 
![image](https://cloud.githubusercontent.com/assets/26572075/24661218/18f15a74-1952-11e7-96f9-dd1e15c70d1a.png)
with --connector-hostname=VcenterIP and esx-hostname=ESX_IP I'm asking memory usage

What am I doing wrong ? :(

**Comment by alliria98** [comment]
Simple question with that kind of command : only my centreon server is allowed to ask some snmp info. Do I have to had my vcenter too ?

**Comment by alliria98** [comment]
Hi everyone,
I'm back here cause I still get the same error, the problem has never been fixed
![image](https://user-images.githubusercontent.com/26572075/31282006-859b7e70-aab1-11e7-9eed-09a3b7a4b071.png)

I suppose I correctly installed "centreon_vmware" plugin, since I can stop/start the service centreon_vmware 
![image](https://user-images.githubusercontent.com/26572075/31282245-3d707ee2-aab2-11e7-8222-4bc19c0bce33.png)

I tried to find any information about my problem in the other thread, but sadly I found nothing.
Can someone help me ? :)

**Comment by alliria98** [comment]
I don't know if I move on or if I just fall into an infinite loop, I've got a new "error" message
![image](https://user-images.githubusercontent.com/26572075/31334276-ee7f4a5a-aced-11e7-938a-e506b7fd5b5c.png)
What did I change ? now the connector isn't my VCenter but my Centreon, and I'm asking directly one of my ESX
I try to find information about the "container" option, but found nothing

A little help would be really appreciated, since I guess I'm not that far from the Graal

**Comment by garnier-quentin** [comment]
Could you give the content of "/etc/centreon/centreon_vmware.pm" file ?

**Comment by alliria98** [comment]
Here we go : 


%centreon_vmware_config = (
    vsphere_server => {
                    'default' => {'url' => 'https://xxx.xxx.xxx.xxx/sdk',
                                 'username' => 'yyyyyyyy',
                                 'password' => 'zzzzzzzz'},
                    }
);
1;


Where "xxx.xxx.xxx.xxx" is the ip address of my VCenter, "yyy" and "zzz" credentials on my VCenter with read-only rights

**Comment by alliria98** [comment]
Mea Culpa, the username was good but it didn't work : I didn't put the full username@domain and that's why I got the error message about container.... Sorry for that
But now, still got another message error : 
![image](https://user-images.githubusercontent.com/26572075/31442117-a85116b8-ae95-11e7-99d5-af458df99089.png)
Gonna search for my own and put the right answer if I found it :)

**Comment by garnier-quentin** [comment]
You can use following option: --no-memory-state

**Comment by alliria98** [comment]
I changed the sampling period for 20 (despite of 300) and that worked too.

Sadly I still got at least one issue : do you why in cli this command works 
![image](https://user-images.githubusercontent.com/26572075/31451037-4c65d7c4-aeab-11e7-8d2b-2e10256b61af.png)

But when I go through the web interface, i got the output : 
![image](https://user-images.githubusercontent.com/26572075/31451076-6741915a-aeab-11e7-8b4c-af0a10fa3734.png)

I tried my command in the web interface in ssh why to magic_command 
`su - centreon-engine -c "command_webinterface_format"`
and it's working I got a good output

**Comment by garnier-quentin** [comment]
Use the mode 'getmap' to know ESX hostnames.

**Comment by alliria98** [comment]
My bas once again... was using the $hostname$ despite of $hostaddress$ macro in my command... Very sorry
Everything's fine now thanks a lot
