### ISSUE TITLE
how filter vm in check vm-tools?

### ISSUE THREAD

**Issue by Gabriel-PROUST** [centreon/centreon-vmware#41]
Bonjour / hello

Je voudrais exclure quelques VM de la sonde VMware vm-tools, mais je n'y arrive pas. 
Voici la command de base :
/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=tools-vm --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='*******'  --vm-hostname='.*' --filter --tools-notinstalled-status='critical'  --tools-notrunning-status='critical'  --tools-notup2date-status='warning' --disconnect-status='ok' --nopoweredon-skip --verbose

qui me renvoie 6 VM not up-to-date, 4 vmtools not running et 3 vmtools not installed.

Je voudrais ôter du check 2 ou 3 VM qui sont des appliance que je ne peux pas modifier. comment faire j'ai essayé ca et ca ne fonctionne pas :
/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=tools-vm --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='*******'  --vm-hostname='.*' --filter --tools-notinstalled-status='critical'  --tools-notrunning-status='critical'  --tools-notup2date-status='warning' --disconnect-status='ok' --nopoweredon-skip --verbose --filter='vm_a_exclure'

Merci d'avance pour l'aide apportée.

Gaby

####################################
I would like to exclude some VM VMware vm-tools probe, but I can't. 
Here is the basic command:
/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=tools-vm --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='*******'  --vm-hostname='.*' --filter --tools-notinstalled-status='critical'  --tools-notrunning-status='critical'  --tools-notup2date-status='warning' --disconnect-status='ok' --nopoweredon-skip --verbose

The result is  6 VM not up-to-date, 4 vmtools not running et 3 vmtools not installed.

I would like to remove the check 2 or 3 VM that are appliance that I can't change. How do I tried that and it does not work:
/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=tools-vm --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='*******'  --vm-hostname='.*' --filter --tools-notinstalled-status='critical'  --tools-notrunning-status='critical'  --tools-notup2date-status='warning' --disconnect-status='ok' --nopoweredon-skip --verbose --filter='vm_a_exclure'

Thanks

Gaby

**Comment by garnier-quentin** [comment]
Hi,

You can exclude with the following syntax (regexp):
```
--vm-hostname='^(?!(vmname1|vmname2)$)'
```

**Comment by Gabriel-PROUST** [comment]
Hi,

Thanks it's OK

Have a good day.

**Comment by garnier-quentin** [comment]
thanks for the feedback!
