### ISSUE TITLE
apps::vmware::connector::plugin - mode memory-vm

### ISSUE THREAD

**Issue by Pheel09** [centreon/centreon-vmware#42]
Hello,

I'm using Centreon vmware plugin to monitor VM memory usage. The plugin works well, here is an output example: 

OK: Memory Total: 16.00 GB Used: 15.93 GB (99.54%) Free: 75.93 MB (0.46%) | 'used'=17100247040B;;;0;17179869184 'overhead'=98094080B;;;0; 'ballooning'=0B;;;0; 'active'=3596315648B;;;0; 'shared'=79767552B;;;0;

However I would like to trigger alert regarding active memory instead of used memory (most relevant). Active memory is shown in perfdata counters.

Is there a way to trigger alerting on active memory instead of used memory?

**Comment by garnier-quentin** [comment]
hi,

Right now you cannot put threshold on other metrics.

**Comment by Pheel09** [comment]
Hi,

Thanks for your fast update. 

According VMware active memory seems to the most relevant metric to monitor (and by the way trigger alert on it). I will try to brain on it.

Is there any enhancement project ongoing on this topic (new centreon-vmware release...)?

**Comment by garnier-quentin** [comment]
It could be yes. But i can't give you a date.

**Comment by Flahx** [comment]
Hi, 
I have the same result. Did you have time to see if is it possible, and maybe have a release date?
Thanks in advance for your return.

Regards,

**Comment by garnier-quentin** [comment]
There is new option on the mode now
