### ISSUE TITLE
ces-plugins-Virtualization-VMWare-client is absent from centreon 3.4 repository

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-vmware#44]
Hello,

Is it normal that the client is present here :
http://yum.centreon.com/standard/3.0/stable/noarch/RPMS/

But not here :
http://yum.centreon.com/standard/3.4/el6/stable/noarch/RPMS/

Thanks

**Comment by garnier-quentin** [comment]
Hi,

I don't manage centreon package. Please ask to your support.

**Comment by ritouret** [comment]
Ok, Thank you Quentin. I'll ask to the support ...
