### ISSUE TITLE
--mode=status-vm : global status isn't the Power status?

### ISSUE THREAD

**Issue by Flahx** [centreon/centreon-vmware#48]
Hi, 
I would like to monitor a Cluster with xx VM and see if one is poweredoff, and also have it's name.
I thought that --mode=status-vm could do this, but when i use it, it tell me that all VM are OK.
Actually, on a specific Cluster i got 22VM and for now, only 7 are poweredON, but the plugin return OK.

Is it normal or do i miss something?

**Comment by garnier-quentin** [comment]
The mode 'count-vm' should be the one ;)
