### ISSUE TITLE
time-host - threshold not working

### ISSUE THREAD

**Issue by mathieuchateau** [centreon/centreon-vmware#50]
Hello,

When setting warning and critical time, it's always getting warning and error state

Sample: generate alert while less than a second time shift:

```
# /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin  --custommode=connector --connector-hostname=127.0.0.1 --verbose --mode time-host --scope-datacenter "MYdatacenter01" --warning-time 60 --critical-time 90
CRITICAL: 'esxi01.mydomain.com' Time offset 0 second(s) : 2017-11-18T14:05:28.044914Z | 'offset'=-0.0449140071868896s;0:60;0:90;0;
'esxi01.mydomain.com' date: 2017-11-18T14:05:28.044914Z, offset: -0.0449140071868896 second(s)
```

-0.0449140071868896 second is below both threshold of 60 an 90

**Comment by Zetun** [comment]
Hello, 

You need to set an interval like this :

`--warning-time=-15:15 --critical-time=-30:30`

**Comment by mathieuchateau** [comment]
@Zetun : Thanks it works
Maybe a good point to update the help message to make format explicit ?

**Comment by garnier-quentin** [comment]
There is a FAQ here : https://github.com/centreon/centreon-plugins/blob/master/docs/en/user/guide.rst#how-can-i-set-threshold-critical-if-value--x-
