### ISSUE TITLE
Install ces-plugin-Virtualization-VMWare-daemon on centreon 3.4

### ISSUE THREAD

**Issue by alex8276** [centreon/centreon-vmware#51]
Hello,
I updated centreon 3.3 to 3.4.
I want install the plugin ces-plugin-Virtualization-VMWare-daemon but  I have an error "no packet available"
How to install this plugin on centreon 3.4 ?

regards ?

**Comment by alex8276** [comment]
Sorry, I reactivate the repo ces-standard-3.0-satble.repo and now it's ok !

**Comment by alex8276** [comment]
Stupid question, but cetreon-vmware must be installed on VMware server or centreon server ?

regards

**Comment by garnier-quentin** [comment]
On the centreon server

**Comment by alex8276** [comment]
Thanks for your answer,
When I use it ?
The command in the doc : erl centreon_plugins.pl --plugin=apps::vmware::connector::plugin  --custommode=connector --connector-hostname=127.0.0.1 --container=default --verbose --mode=tools-vm --display-description --vm-hostname='prd' --filter
Error:
UNKNOWN: Cannot load module --plugin. Can't locate apps/vmware/connector/plugin.pm in @inc (@inc contains: /usr/lib/nagios/plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/nagios/plugins/centreon/plugins/misc.pm line 221

So I search and i found the issue 5587 and  test : 
/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin
Error: UNKNOWN: Need to specify '--mode' or '--dyn-mode' option

**Comment by cgagnaire** [comment]
Hi @alex8276,
On Centreon 3.4 you need to install both daemon and plugin using this 2 packages : 
centreon-plugin-Virtualization-VMWare-daemon-2.4.0-1.el7.centos.noarch
centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20171208-1.el7.noarch

**Comment by cgagnaire** [comment]
Hi @alex8276,
Did you manage to install those ?

**Comment by alex8276** [comment]
Hi cgagnaire,
sorry I didn't view your responses.
Yes, I had manage to install the plugin.
Thanks

**Comment by cgagnaire** [comment]
No worries, thanks!
