### ISSUE TITLE
issue with installing vmware-centreon

### ISSUE THREAD

**Issue by VuNgocTan** [centreon/centreon-vmware#59]
Hi guys, I follow the guide to install it, but I stuck at this step for days:

> yum install ces-plugins-Virtualization-VMWare-client

it says that:

> Resolving Dependencies
--> Running transaction check
---> Package ces-plugins-Virtualization-VMWare-client.noarch 0:2.3.1-1.el6 will be installed
--> Processing Dependency: perl(ZMQ::LibZMQ3) for package: ces-plugins-Virtualization-VMWare-client-2.3.1-1.el6.noarch
Package perl-ZMQ-LibZMQ3-1.19-1.el6.x86_64 is obsoleted by perl-ZMQ-LibZMQ4-0.01-1.el6.x86_64 which is already installed
--> Finished Dependency Resolution
Error: Package: ces-plugins-Virtualization-VMWare-client-2.3.1-1.el6.noarch (ces-standard-noarch)
           Requires: perl(ZMQ::LibZMQ3)
           Available: perl-ZMQ-LibZMQ3-1.12-1.el6.1.x86_64 (epel)
               perl(ZMQ::LibZMQ3) = 1.12
           Available: perl-ZMQ-LibZMQ3-1.19-1.el6.x86_64 (centreon-stable)
               perl(ZMQ::LibZMQ3)
 You could try using --skip-broken to work around the problem
** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:
centreon-plugin-Virtualization-VMWare-daemon-2.4.0-1.el7.centos.noarch is a duplicate with centreon-plugin-Virtualization-VMWare-daemon-2.4.0-1.el6.noarch

What can I do to solve this? 
Thanks

**Comment by cgagnaire** [comment]
Hi @VuNgocTan,
You should install centreon-plugin-Virtualization-Vmware2-Connector-Plugin instead.
We will update the documentation.
