### ISSUE TITLE
--plugin=apps::vmware::connector::plugin  --mode=alarm-datacenter / exclude filter

### ISSUE THREAD

**Issue by inferno66** [centreon/centreon-vmware#62]
Hello,

I'm using  --mode=alarm-datacenter in order to get alarms.
This is working perfectly.

But I need to filter in order to exlude some alarms. For example I don't want the "Virtual machine CPU usage" alarms.
I know the easiest way is to configure them in Vcenter but unfortunnaly it's managed by another compagny and we don't have access alarms configurations (and they don't wan't to change de config)

Is it possible?

Best regards

**Comment by garnier-quentin** [comment]
You can filter alarms by name in warning-status and --critical-status.
