### ISSUE TITLE
Can't get a single datastore with mode datastore-vm

### ISSUE THREAD

**Issue by stefanotoro** [centreon/centreon-vmware#63]
Centreon 2.18
centreon-plugin-Virtualization-Vmware2-Connector-Plugin 20171208

Backend storage is a VMware Virtual SAN

./centreon_vmware_connector_client.pl --mode datastore-vm --connector-hostname 127.0.0.1 --vm-hostname vl022831

UNKNOWN: Can't get a single datastore

The problem does not exist if the storage is a VMFS

**Comment by garnier-quentin** [comment]
It should be ok with last version which supports vsan.
