### ISSUE TITLE
Login to VirtualCenter server failed: Server version unavailab

### ISSUE THREAD

**Issue by sder73** [centreon/centreon-vmware#69]
Hello

I am using centreon vmware
my version are 
ces-plugins-Virtualization-VMWare-client-2.3.1-1.el6.noarch
ces-plugins-Virtualization-VMWare-daemon-2.3.1-1.el6.noarch
on CentOS release 6.7 (Final)

I have define /etc/centreon/centreon_vmware.pm
[root@frparsumon01p log]# more  /etc/centreon/centreon_vmware.pm
%centreon_vmware_config = (
        vsphere_server => {
                        'ale' => {'url' => 'https://x.x.x.x/sdk',
                                     'username' => 'monitoring',
                                     'password' => 'eeeeeee'}
                        }

);

1;

When I test i have 
# wget https://x.x.x.x:443/sdk/vimService.wsdl --no-check-certificate
--2018-04-19 11:10:54--  https:/x.x.x.x/sdk/vimService.wsdl
Connecting to 10.67.129.100:443... connected.
WARNING: cannot verify 10.67.129.100’s certificate, issued by “/C=US/ST=California/L=Palo Alto/O=VMware, Inc./CN=localhost.localdom CA 3801b373/emailAddress=ssl-certificates@vmware.com”:
  Unable to locally verify the issuer’s authority.
WARNING: no certificate subject alternative name matches
        requested host name “x.x.x.x”.
HTTP request sent, awaiting response... 200 OK
Length: 545 [text/xml]
Saving to: “vimService.wsdl.1”

100%[================================================================================================================================================================================================>] 545         --.-K/s   in 0s

2018-04-19 11:10:54 (71.6 MB/s) - “vimService.wsdl.1” saved [545/545]

So it is ok 
but in  /var/log/centreon/centreon_vmware.log

2018-04-19 11:27:22 - 'ale' Vsphere connection in progress
2018-04-19 11:27:22 - 'ale' Login to VirtualCenter server failed: Server version unavailable at 'https://10.67.129.100:443/sdk/vimService.wsdl' at /usr/local/share/perl5/VMware/VICommon.pm line 545.

2018-04-19 11:27:32 - 'ale' Vsphere connection in progress
2018-04-19 11:27:32 - 'ale' Login to VirtualCenter server failed: Server version unavailable at 'https://10.67.129.100:443/sdk/vimService.wsdl' at /usr/local/share/perl5/VMware/VICommon.pm line 545.

2018-04-19 11:27:42 - 'ale' Vsphere connection in progress
2018-04-19 11:27:42 - 'ale' Login to VirtualCenter server failed: Server version unavailable at 'https://10.67.129.100:443/sdk/vimService.wsdl' at /usr/local/share/perl5/VMware/VICommon.pm line 545.

So could you help me

Thank you

**Comment by cgagnaire** [comment]
Hi @sder73,
What is the versions of your vCenter server and the perl SDK installed on your poller ?
You should also use centreon-plugin-Virtualization-VMWare-daemon and centreon-plugin-Virtualization-Vmware2-Connector-Plugin as they are latest versions.

**Comment by sder73** [comment]
Hello
I use
perl-VMware-vSphere-5.1.0-780721.1.el6.x86_64 and vCenter version is 5.5.

Is the new version run under centos 6 ?

Thank you

**Comment by sder73** [comment]
Hello
Have you some idea for me

Thank you

**Comment by sder73** [comment]
Hello

The package needs this version Compress::Zlib 2.037 or newer and I do not find it for el6

Best Regard

**Comment by koutsupcom** [comment]
Hello,

You must disable checking globally by editing https.pm of the LWP module:
sudo vi  /usr/share/perl5/LWP/Protocol/https.pm
Then Look for the following line $ssl_opts{SSL_verify_mode} ||= 1;
and change it to $ssl_opts{SSL_verify_mode} ||= 0;

if not work add $ssl_opts{SSL_verify_mode} ||= 0;  after this line   my %ssl_opts = %{$self->{ua}{ssl_opts} || {}}; in _extra_sock_opts function.

Best Regard

**Comment by garnier-quentin** [comment]
Do you still have the problem ?

**Comment by garnier-quentin** [comment]
You can re-open it if you still have the issue.
