### ISSUE TITLE
Error on Alarm-host for one ESX

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-vmware#7]
Here the command and error message:
The plugin got the last version :-)

 /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=alarm-host --custommode=connector --connector-hostname=127.0.0.1 --container=xxxx --verbose
UNKNOWN: VMWare error (verbose mode for more details) | 'alarm_warning'=0;;;0; 'alarm_critical'=0;;;0;
Can't call method "type" on an undefined value at /usr/local/share/perl5/VMware/VICommon.pm line 1501.
Checking host xxx.yyy.com
    0 warn alarm(s) found(s) - 0 critical alarm(s) found(s)

Thanks in advance.

**Comment by matthieu-robin** [comment]
It works on other esxi. sorry

**Comment by garnier-quentin** [comment]
fix on version 2.1.0 ;)
