### ISSUE TITLE
DATASTORE-USAGE : free space threshold

### ISSUE THREAD

**Issue by maximeuri** [centreon/centreon-vmware#72]
Hello,

we have an inconsistency with this plugin's module. 

Command used is : 
/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=XXX --container=YYY --mode=datastore-usage --units=B --free --critical=100000000 --warning=300000000

Then, all datastores whose free space are more than 100000000B return critical alert.

Is it a known issue ?

Thanks,
Best regards.

Maxime U.

**Comment by cgagnaire** [comment]
Hi @maximeuri,
Our plugins use the Nagios guidelines for thresholds.
For what you want to do, you have to set thresholds like this : `--critical=100000000: --warning=300000000:`
Take a look to https://nagios-plugins.org/doc/guidelines.html
