### ISSUE TITLE
response format incorrect - need connector vmware version >= 3.x.x

### ISSUE THREAD

**Issue by gerpion** [centreon/centreon-vmware#74]
Hello,

I'm trying to make the vmware plugin to work without success.
I'm using the last centreon version.

cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)

centreon-engine-18.10.0-4.el7.centos.x86_64
centreon-plugin-Virtualization-VMWare-daemon-2.4.0-1.el7.centos.noarch
centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20190111-102147.el7.centos.noarch

[root@sql-trk-02 plugins]# /usr/bin/centreon_vmware.pl
2019-02-15 17:57:54 - Create vsphere sub-process for 'default'
2019-02-15 17:57:54 - [Server accepting clients]
2019-02-15 17:57:54 - 'default' init begin
2019-02-15 17:57:54 - 'default' init done
2019-02-15 17:57:54 - 'default' Vsphere connection in progress
2019-02-15 17:57:54 - 'default' Vsphere connection ok
2019-02-15 17:57:54 - 'default' Create perf counters cache in progress
2019-02-15 17:57:55 - 'default' Create perf counters cache done

Seems OK.

./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --container=default --connector-hostname=127.0.0.1 --mode=list-datastores
Got a timeout and this in the log :
2019-02-15 17:58:12 - 'default' SOAP request error - possibly a protocol issue: Server closed connection without sending any data back at /usr/share/perl5/vendor_perl/Net/HTTP/Methods.pm line 373.

I sometimes also got this error : 
Use of uninitialized value in numeric eq (==) at /usr/share/perl5/vendor_perl/centreon/vmware/cmdbase.pm line 75.

After restarting the centreon_vmware i have this error too: 

systemctl restart centreon_vmware 
./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --container=default --connector-hostname=127.0.0.1 --mode=list-datastores
UNKNOWN: response format incorrect - need connector vmware version >= 3.x.x

Any clues ?

**Comment by garnier-quentin** [comment]
You have an incompatibility between the plugin and the centreon vmware connector. You can:
* upgrade the centreon vmware connector version (use the last one on github)
* downgrade the centreon-plugins.

**Comment by gerpion** [comment]
Hello Quentin,
I've got the lastest centreon vmware connector version from rpm.

-bash-4.2$ sudo yum update
Loaded plugins: fastestmirror
Determining fastest mirrors
 * base: ftp.pasteur.fr
 * extras: centos.mirrors.proxad.net
 * updates: centos.mirrors.proxad.net
base                                                                                      | 3.6 kB  00:00:00
centos-sclo-rh                                                                            | 3.0 kB  00:00:00
centos-sclo-sclo                                                                          | 2.9 kB  00:00:00
centreon-stable                                                                           | 2.9 kB  00:00:00
centreon-stable-noarch                                                                    | 2.9 kB  00:00:00
extras                                                                                    | 3.4 kB  00:00:00
updates                                                                                   | 3.4 kB  00:00:00
No packages marked for update

and the last plugin version from git.

git clone https://github.com/centreon/centreon-plugins.git

So do i still need to take your advices ?

Regards

**Comment by gerpion** [comment]
[root@sql-trk-02 ~]# rpm -qa | grep -i '.*cen.*vmw.*'
centreon-plugin-Virtualization-VMWare-daemon-2.4.0-1.el7.centos.noarch
centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20190111-102147.el7.centos.noarch

**Comment by garnier-quentin** [comment]
The last vmware connector is not in the repository. You can download it:
https://share.centreon.com/public/c426d4

The procedure for upgrading:
```
# yum update centreon-plugin-Virtualization-VMWare-daemon-3.0.0-1.el7.centos.noarch.rpm
# systemctl stop centreon_vmware
# systemctl daemon-reload
# chown centreon:centreon /var/log/centreon/centreon_vmware.log
# chown -R centreon:centreon /tmp/centreon_vmware
# systemctl start centreon_vmware
```

**Comment by gerpion** [comment]
Awesome, it's working, thanks alot Quentin.

**Comment by da-friedl** [comment]
Hi,

why is the connector in version 3 not available in the official repository? when do you plan to make it available in the repo?

I'm aksing because we have about 50(!) satellites shared with our customers and it would be very nice if we simply could update via yum. For the solution above we have to write & test a new ansible playbook (not the problem itself, but if you plan to release the new connector within the next few days in the official repo we may save the time)

Thank you very much and best regards
Daniel

**Comment by garnier-quentin** [comment]
The connector is not available in rpm because the plugin is not released also.

**Comment by romsworld** [comment]
Hi,

Do you rpm for centos 6 ?

Thanks
