### ISSUE TITLE
centreon-plugin-Virtualization-VMWare-daemon.noarch 3.0

### ISSUE THREAD

**Issue by boogaaloo** [centreon/centreon-vmware#78]
Hello,

I made an update to Centreon and nothing else works with the vmware plugin. I uninstalled centreon-plugin-Virtualization-VMWare-daemon.noarch 3.0.0 but can not find the old version
Here's my question: where can I find the latest version centreon-plugin-Virtualization-VMWare-daemon before version 3.0?
Thank you

**Comment by garnier-quentin** [comment]
It should work. After upgrading the daemon package, you need to do:
```
# yum update centreon-plugin-Virtualization-VMWare-daemon-3.0.0-1.el7.centos.noarch.rpm
# systemctl stop centreon_vmware
# systemctl daemon-reload
# chown centreon:centreon /var/log/centreon/centreon_vmware.log
# chown -R centreon:centreon /tmp/centreon_vmware
# systemctl start centreon_vmware
```

**Comment by boogaaloo** [comment]
"_After upgrading the daemon package_"
Can you specify packages to upgrade ?
Thank you

**Comment by garnier-quentin** [comment]
Following on the poller:
```
 yum update centreon-plugin-Virtualization-VMWare-daemon centreon-plugin-Virtualization-Vmware2-Connector-Plugin
```

**Comment by boogaaloo** [comment]
There is no upgrade for _centreon-plugin-Virtualization-Vmware2-Connector-Plugin_
Is this normal ?
My version is _centreon-plugin-Virtualization-VMWare-daemon.noarch **0:3.0.0-20190221161610**.el7.centos_
Is it OK ?

**Comment by garnier-quentin** [comment]
There is a new Connector-Plugin also

**Comment by boogaaloo** [comment]
Thank you for your help. 
And... where is it ;)
