### ISSUE TITLE
centreon-plugin-Virtualization-Vmware2-Connector-Plugin - Update

### ISSUE THREAD

**Issue by boogaaloo** [centreon/centreon-vmware#79]
Hello,

I open a new issue.
I upgraded centreon-plugin-Virtualization-VMWare-daemon (by yum). Then I updated the part of the vmware plugins - github ) in order to have centreon-plugin-Virtualization-Vmware2-Connector-Plugin up-to-date.
Then I follow this :
```
# systemctl stop centreon_vmware
# systemctl daemon-reload
# chown centreon:centreon /var/log/centreon/centreon_vmware.log
# chown -R centreon:centreon /tmp/centreon_vmware
# systemctl start centreon_vmware
```
Nothing happen ! except this error :
`UNKNOWN: Container connection problem`
When i do `journalctl -u centreon_vmware` :
`Cannot open file /var/log/centreon/centreon_vmware.log: Permission non accordée`

`-rw-r--r-- 1 centreon centreon 11363178 25 mars  12:04 /var/log/centreon/centreon_vmware.log`

This update is a bit messy...
Thank you for your enlightenment !

**Comment by boogaaloo** [comment]
I uninstalled everything and reinstalled everything :
```
- (1/2): centreon-plugin-Virtualization-Vmware2-Connector-Plugin-2019022     
- (2/2): centreon-plugin-Virtualization-VMWare-daemon-3.0.0-201902211616
```
Then 
```
# systemctl stop centreon_vmware
# systemctl daemon-reload
# chown centreon:centreon /var/log/centreon/centreon_vmware.log
# chown -R centreon:centreon /tmp/centreon_vmware
# systemctl start centreon_vmware
```
It doesn't work....

**Comment by garnier-quentin** [comment]
Could you give me plugin output error ? VMWare daemon is running ?

**Comment by boogaaloo** [comment]
When updating the packages, the file `/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl` appears to be ignored. I had to add it manually and now it works.
Thanks again for your help.

**Comment by garnier-quentin** [comment]
You're welcome
