### ISSUE TITLE
Add the posibility to monitor the storagehealth and temperature.

### ISSUE THREAD

**Issue by boubou** [centreon/centreon-vmware#8]
Hi Quentin,
It would be very great if you can add an option to monitor the storagehealth of datastores (I would like to be alerted when a raid become degraded) and temperature of ESXis hosts.

check_vmware_api from consol.de have this possibility.

Could you add it to centreon_vmware ?

Thanks you very much in advance and merry christmas!

**Comment by garnier-quentin** [comment]
Already in the healthhost. I will add it in health host plugin.
