### ISSUE TITLE
Only listen to localhost

### ISSUE THREAD

**Issue by silradsi** [centreon/centreon-vmware#81]
Hi there,

I've been through the code and documentation, but didn't find any way to make the daemon only listen to localhost. It's currently listening to all IPs, which for me is a security issue. Is there a way to listen only to 127.0.0.1 ?

Best regards,
silradsi

**Comment by garnier-quentin** [comment]
You cannot. You need to change following line:
```
zmq_bind($frontend, 'tcp://*:' . $centreon_vmware->{centreon_vmware_config}->{port});
```
