### ISSUE TITLE
vsphere_server config stanza key is case sensitive

### ISSUE THREAD

**Issue by hecko** [centreon/centreon-vmware#83]
`%centreon_vmware_config = (
    port => 5701,
    vsphere_server => {
        'default' => {
`

is not the same as

`%centreon_vmware_config = (
    port => 5701,
    vsphere_server => {
        'DEFAULT' => {
`

I believe these should be case insensitive.
I believe the behavior of the config being case sensitive is contraintuitive.

**Comment by garnier-quentin** [comment]
I ll do a patch.

**Comment by garnier-quentin** [comment]
Available in version 3.2.2
