### ISSUE TITLE
Display both Used and Free space of datastore

### ISSUE THREAD

**Issue by HNK-HerisG01** [centreon/centreon-vmware#84]
Hello,

I'm using the latest versions of the centreon-vmware plugin and the connector, and I am wondering:

I am monitoring datastore usages on a vcenter.

- without the '--free' option, the plugin returns 'used' and 'provisionned' performance datas.

- with the 'free' option, the plugin returns 'free' and 'provisionned' performance datas but not the 'used' value.

I need to have the warning and critical thresholds on "space left" values but also need to monitor what space is used, and I don't really need the provisionned information.

Is there a way to get performance data values for both 'used' and 'free' ? They are nicely displayed in the status section but I can't seem to find a way to have them both

Thanks for your help,
Best regards,

**Comment by garnier-quentin** [comment]
I can change the plugin yes to do that.

**Comment by HNK-HerisG01** [comment]
Hello,

Thanks for the feedback.

Yes if it doesn't take too much effort, it would be lifesaving !

Regards,

**Comment by garnier-quentin** [comment]
I have done the patch on https://github.com/centreon/centreon-plugins
Could you test it ?

**Comment by HNK-HerisG01** [comment]
I just tested, it works perfectly, thank you so much !

Have a great day,
Best regards.

**Comment by garnier-quentin** [comment]
Thanks for the feedback!

**Comment by HNK-HerisG01** [comment]
Just to let you know, I think there was a copy-paste typo in apps/vmware/connector/mode/datastoreusage.pm on line 48:  

my ($total_free_value, $total_free_unit) = $self->{perfdata}->change_bytes(value => $self->{result_values}->{used_space_absolute}); 

instead of  
my ($total_free_value, $total_free_unit) = $self->{perfdata}->change_bytes(value => $self->{result_values}->{free_space_absolute});

generating the same value as the 'Used' one in the detailed status.

Best Regards,
