### ISSUE TITLE
Mode memory-vm - Perfdata output

### ISSUE THREAD

**Issue by Speed25** [centreon/centreon-vmware#88]
Hello,

I try to catch 2 metrics : Memory consumed Usage and Memory active Usage. I can see metrics in "Status Information" : 
`OK: Virtual machine '172.17.4.15 - Centreon-Central' : [connection state connected][power state poweredOn] - Memory consumed Usage Total: 2.00 GB Used: 1.98 GB (99.23%) Free: 15.83 MB (0.77%) - Memory active Usage Total: 2.00 GB Used: 640.34 MB (31.27%) Free: 1.37 GB (68.73%) - Memory overhead: 40.47 MB - Memory ballooning: 0.00 B - Memory shared: 16.04 MB`

I want sames metrics in perf data output (i use Graphite + Grafana to play with metrics) but i have this : 
`'used'=2130883584B;;;0;2147483648
'used'=671443968B;;;0;2147483648
'overhead'=42437632B;;;0;
'ballooning'=0B;;;0;
'shared'=16822272B;;;0;`

Why do we have 2 times 'used' ? Can we rename a metrics with 'used_active' and 'used_consumed' for example ? 

Best Regards,

**Comment by garnier-quentin** [comment]
It had been fixed in last version i think. Update centreon_plugins.

**Comment by Speed25** [comment]
I missed the last update. 

Thanks, it's work !
