### ISSUE TITLE
[Mode] Memory-vm and ballooning

### ISSUE THREAD

**Issue by alliria98** [centreon/centreon-vmware#89]
Hi everyone,
I have few ESX servers and I want to monitore if one of them is starting to balloon

I found in the output of memory-vm mode that i can get this information :
![image](https://user-images.githubusercontent.com/26572075/87793433-8e110480-c845-11ea-9071-ce7e1641db53.png)
Great ! But I have two questions : 
1. First, how can I manage the output to get into critical state ONLY when ballooning is different to 0 ?
2. Second, is it possible to remove the "--vm-hostname" option to get ALL VM from 1 ESX, and trigger only if one of them get ballooning ?

Thanks in advance for your answer :)

**Comment by garnier-quentin** [comment]
You can use following option: ```--critical-ballooning=0```
You can scope on one ESX with: ```--scope-host='plop'```

**Comment by alliria98** [comment]
The option seems not be available ? 
![image](https://user-images.githubusercontent.com/26572075/87797072-8142df80-c84a-11ea-9413-c16027f4a30e.png)
I tried "yum update centreon-vmware" but it seems to already be up to date

**Comment by garnier-quentin** [comment]
It's not the last version. Because it's working for me

**Comment by alliria98** [comment]
May you could help me upgrading centreon-vmware ?
When I attemp upgrading the package with :
yum update centreon-vmware
yum upgrade centreon-vmware

Both commands return "nothing to do" :(

**Comment by garnier-quentin** [comment]
Packages are:
```
yum update centreon-plugin-Virtualization-VMWare-daemon.noarch
yum update centreon-plugin-Virtualization-Vmware2-Connector-Plugin.noarch
```
