### ISSUE TITLE
CPU and datastore cluster information

### ISSUE THREAD

**Issue by chi-miel** [centreon/centreon-vmware#90]
Hello,

1. Is it possible to get cluster cpu usage ?
I tried with vpu-cm and cpu-host but these monitor cpu usage by vm or host not the sum of cpu usage in a cluster. Also , i tried  with option --warning-total-cpu but is the total au cpu by host or vm ?

2. And is it possible to get datastore free space in "datastore cluster" ?
I try to get all free space in cluster not by datastore.

Thank you

**Comment by chi-miel** [comment]
Hello,

Has anyone ever had this situation before? 

Thank you

**Comment by garnier-quentin** [comment]
Available in version 3.2.2 (cluster-cpu mode)
