### ISSUE TITLE
Login to VirtualCenter failed

### ISSUE THREAD

**Issue by Meistercoach83** [centreon/centreon-vmware#91]
`'default' Login to VirtualCenter server failed: Server version unavailable at 'https://wapllvcs03.saarland.de:443/sdk/vimService.wsdl' at /usr/local/share/perl5/VMware/VICommon.pm line 734.
`

Hello! In my centreon/centreon_vmware.log there are many errors like the above. What shall I do to solve this issue?

**Comment by garnier-quentin** [comment]
Could you do get the file 'https://wapllvcs03.saarland.de:443/sdk/vimService.wsdl' with wget ?

**Comment by Meistercoach83** [comment]
No, it´s not possible. 
But I was able to get this response:
`<?xml version="1.0" encoding="UTF-8" ?>

<definitions targetNamespace="urn:vim25Service"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:interface="urn:vim25"
>
   <import location="vim.wsdl" namespace="urn:vim25" />
   <service name="VimService">
      <port binding="interface:VimBinding" name="VimPort">
         <soap:address location="https://localhost/sdk/vimService" />
      </port>
   </service>
</definitions>
`

with this function call: 
`wget wapllvcs03.saarland.de/sdk/vimService.wsdl --no-check-certificate`

**Comment by garnier-quentin** [comment]
Could you add a debug in '/usr/local/share/perl5/VMware/VICommon.pm' to see the content of variable '$@'

**Comment by Meistercoach83** [comment]
how can I do that?

**Comment by Meistercoach83** [comment]
?

**Comment by Meistercoach83** [comment]
Wenn es eine Rolle spielt: Unser vmware-Server läuft auf https://***:8443

**Comment by Meistercoach83** [comment]
@garnier-quentin The issue is open for 9 days now and I´d like to finish the vmware integration...

**Comment by garnier-quentin** [comment]
You can send me an email and i could try to remote session if you can

**Comment by garnier-quentin** [comment]
Change the port in centreon vmware configuration

**Comment by Meistercoach83** [comment]
The port change didn´t solve the problem - but I was able to change the url to get the results:

`'url' => 'http**s**://ServerName:**8443**/sdk',`
