### ISSUE TITLE
apps::vmware::connector::plugin - mode net-vm

### ISSUE THREAD

**Issue by Maekess** [centreon/centreon-vmware#93]
Hi,

From last git pull files, when I use :
./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --connector-hostname=127.0.0.1 --vm-hostname=VM --mode='net-vm' --case-insensitive --vsphere-address='VCENTER' --vsphere-username=USER --vsphere-password=PASSWORD --debug

I get :
UNKNOWN: Unknown method name 'netvm' |
{"data":{},"short_message":"Unknown method name 'netvm'","extra_message":"","vmware_connector_version":"3.1.2","code":1}

netvm.pm is present in
./apps/vmware/connector/mode/netvm.pm

All other mods are working properly.

Thx

**Comment by garnier-quentin** [comment]
Please update vmware connector to version 3.2.1

**Comment by Maekess** [comment]
Perfectly done, thanks

**Comment by garnier-quentin** [comment]
thanks for the feeedback!
