### ISSUE TITLE
[Question metric vcenter]

### ISSUE THREAD

**Issue by chi-miel** [centreon/centreon-vmware#97]
Hello,

I have few questions about how metrics are retrieve from vcenter :  

1.  for an CPU VM, i look up in the code in order to find which metrics are retrieve, in the file centreon/vmware/cmdcpuvm.pm.
  I found these : 
> `[{'label' => 'cpu.usage.average', 'instances' => \@instances},
>  {'label' => 'cpu.usagemhz.average', 'instances' => \@instances},
>  {'label' => 'cpu.ready.summation', 'instances' => \@instances}],`
> 
> According to the documentation https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.monitoring.doc/GUID-25800DE4-68E5-41CC-82D9-8811E27924BC.html , these metrcis are available in metrics level 1.
> 
> But i found a issue about increase metrics level (https://github.com/centreon/centreon-vmware/issues/13 )
> 
> So my question is why there need to increase ?

2. In slack, I have been recommended to use the argument "--time-shift" , i set ip to 30 secondes and it's work but i don't understand why shifting may fix the problem ? In the Help i found more information "Can shift the time. We the following option you can average X". why it's refer to average some counter ?

Thank you.

**Comment by garnier-quentin** [comment]
The isse was for memory mode (not cpu). In memory mode, there is a metric with level above 1.

**Comment by chi-miel** [comment]
Hello,

Ah yes sorry, i enconter this same error message ("Cannot get counter") sometime for cpu metrics. I checked my NTP, is synchronised. So i use argument "--time-shift" and it's work. Can you explain what this argument do ? (average counter from x secondes or get counter from shift x secondes )

In fact, i also monitor memory and i don't level up my metrics to 2, so i don't understant very well how it's work because but i think "--time-shift" can get memory metrics.

Thank you

**Comment by garnier-quentin** [comment]
To get a metric, i provide a timeframe. But sometimes, the vcenter (or ESXi) doesn't have a value for current time. So you can shift the timeframe (to get an "older" value).

**Comment by chi-miel** [comment]
Ok, so in my case i use, for cpu and memory : --sampling-period='20' --time-shift=30 (Without increase metric level). 

It's mean, the timeframe is 20 seconds and it's drift to 30 seconds at each check ?

**Comment by garnier-quentin** [comment]
Exactly. And with --sampling-period='20', metric level is not applied.

**Comment by chi-miel** [comment]
ok Thank you very for this details !

In fact my adminstrator doesn't want increase metric level so i must found an ohter solution =) !

i will use --sampling-period, juste need some test to find 'stable' status.
